### PR TITLE
Using relative paths

### PR DESCRIPTION
**Pull request by plribeiro3000**
relates to fog/fog#3430

### CODE REVIEW

**Comment by plribeiro3000** [comment]
@jhellan Could you please do a new release with those changes?

Thanks!

**Comment by jhellan** [comment]
Am traveling. Probably Monday

Jon

**Comment by plribeiro3000** [comment]
No problem. Monday is good. =)

Thanks!

**Comment by jhellan** [comment]
Release 0.0.4 pushed to rubygems.org

**Comment by plribeiro3000** [comment]
Awesome @jhellan . Thank you!

**Pull request merged**
